server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/missyou?useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

missyou:
  security:
    jwt-key: yjq
    token-expired-in: 86400000
  order:
    max-sku-limit: 777
    pay-time-limit: 3600
    pay-callback-host: http://talein.com
    pay-callback-path: v1/payment/wx/notify


