server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/missyou?useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  redis:
    localhost: localhost
    port: 6379
    database: 0
    password:
    listen-pattern: __keyevent@0__:expired


missyou:
  security:
    jwt-key: yjq
    token-expired-in: 86400000
  order:
    max-sku-limit: 777
    pay-time-limit: 10
    pay-callback-host: http://talein.com
    pay-callback-path: v1/payment/wx/notify

#rocketmq:
#  consumer:
#    consumer-group: SleeveCousumerGroup
#  producer:
#    producer-group: SleeveProducerGroup
#  namesrv-addr: 127.0.0.1:9876

